export const FIX_TAGS = {
  1: "Account",
  2: "AdvId",
  3: "AdvRefID",
  4: "AdvSide",
  5: "AdvTransType",
  6: "AvgPx",
  7: "BeginSeqNo",
  8: "BeginString",
  9: "BodyLength",
  10: "CheckSum",
  11: "ClOrdID",
  12: "Commission",
  13: "CommType",
  14: "CumQty",
  15: "Currency",
  16: "EndSeqNo",
  17: "ExecID",
  18: "ExecInst",
  19: "ExecRefID",
  20: "ExecTransType",
  21: "HandlInst",
  22: "SecurityIDSource",
  23: "IOIID",
  24: "IOIRefID",
  25: "IOIQty",
  26: "IOITransType",
  27: "LastCapacity",
  28: "LastMkt",
  29: "LastPx",
  30: "LastShares",
  31: "LeavesQty",
  32: "LastShares",
  33: "LinesOfText",
  34: "MsgSeqNum",
  35: "MsgType",
  36: "NewSeqNo",
  37: "OrderID",
  38: "OrderQty",
  39: "OrdStatus",
  40: "OrdType",
  41: "OrigClOrdID",
  42: "OrigTime",
  43: "PossDupFlag",
  44: "Price",
  45: "RefSeqNum",
  46: "RelatdSym",
  47: "Rule80A",
  48: "SecurityID",
  49: "SenderCompID",
  50: "SenderSubID",
  51: "SendingDate",
  52: "SendingTime",
  53: "Shares",
  54: "Side",
  55: "Symbol",
  56: "TargetCompID",
  57: "TargetSubID",
  58: "Text",
  59: "TimeInForce",
  60: "TransactTime",
  61: "Urgency",
  62: "ValidUntilTime",
  63: "SettlType",
  64: "SettlDate",
  65: "SymbolSfx",
  66: "ListID",
  67: "ListSeqNo",
  68: "TotNoOrders",
  69: "ListExecInst",
  70: "AllocID",
  71: "AllocTransType",
  72: "NoOrders",
  73: "NoAllocs",
  74: "ExecBroker",
  75: "TradeDate",
  76: "ExecID",
  77: "OpenClose",
  78: "NoAllocs",
  79: "AllocAccount",
  80: "AllocQty",
  81: "ProcessCode",
  82: "NoRpts",
  83: "RptSeq",
  84: "CxlQty",
  85: "NoDlvyInst",
  86: "DlvyInst",
  87: "AllocQty",
  88: "AllocAcc",
  89: "AllocStatus",
  90: "AllocRejCode",
  91: "Signature",
  92: "SecureDataLen",
  93: "SecureData",
  94: "SignatureLength",
  95: "EmailType",
  96: "RawDataLength",
  97: "RawData",
  98: "PossResend",
  99: "EncryptMethod",
  100: "StopPx",
  102: "CxlRejReason",
  103: "OrdRejReason",
  104: "IOIQualifier",
  105: "WaveNo",
  108: "HeartBtInt",
  109: "ClientID",
  111: "MaxFloor",
  112: "TestReqID",
  113: "ReportToExch",
  114: "LocateReqd",
  115: "OnBehalfOfCompID",
  116: "OnBehalfOfSubID",
  117: "QuoteID",
  118: "NetMoney",
  119: "SettlCurrAmt",
  120: "SettlCurrency",
  121: "ForexReq",
  122: "OrigSendingTime",
  123: "GapFillFlag",
  124: "NoExecs",
  125: "CxlType",
  128: "DeliverToCompID",
  129: "DeliverToSubID",
  131: "QuoteReqID",
  132: "BidPx",
  133: "OfferPx",
  134: "BidSize",
  135: "OfferSize",
  136: "NoMiscFees",
  137: "MiscFeeAmt",
  138: "MiscFeeCurr",
  139: "MiscFeeType",
  140: "PrevClosePx",
  141: "ResetSeqNumFlag",
  142: "SenderLocationID",
  143: "TargetLocationID",
  144: "OnBehalfOfLocationID",
  145: "DeliverToLocationID",
  146: "NoRelatedSym",
  147: "Subject",
  148: "Headline",
  149: "URLLink",
  150: "ExecType",
  151: "LeavesQty",
  152: "CashOrderQty",
  153: "AllocAvgPx",
  154: "AllocNetMoney",
  155: "SettlCurrFxRate",
  156: "SettlCurrFxRateCalc",
  157: "NumDaysInterest",
  158: "AccruedInterestRate",
  159: "AccruedInterestAmt",
  160: "SettlInstMode",
  161: "AllocText",
  162: "SettlInstID",
  163: "SettlInstTransType",
  164: "EmailThreadID",
  165: "SettlInstSource",
  166: "SettlLocation",
  167: "SecurityType",
  168: "EffectiveTime",
  169: "StandInstDbType",
  170: "StandInstDbName",
  171: "StandInstDbID",
  172: "SettlDeliveryType",
  173: "StandInstDbFlag",
  174: "DlvyInstType",
  175: "AllocCustomerCapacity",
  176: "TierCode",
  177: "UnitofMeasure",
  178: "TimeUnit",
  179: "SecurityExchange",
  180: "PositionEffect",
  181: "PrevClosePx",
  182: "NoPositions",
  183: "PosType",
  184: "LongQty",
  185: "ShortQty",
  186: "PosQtyStatus",
  187: "PosAmtType",
  188: "PosAmt",
  189: "PosTransType",
  190: "PosReqID",
  191: "NoPosAmt",
  192: "AutoAcceptIndicator",
  193: "AllocReportID",
  194: "NoNested2PartyIDs",
  195: "Nested2PartyID",
  196: "Nested2PartyIDSource",
  197: "Nested2PartyRole",
  198: "NoNested2PartySubIDs",
  199: "Nested2PartySubID",
  200: "Nested2PartySubIDType",
  7620: "StrategyType",
  7657: "StrategyVersion",
  7722: "AlgoParamFlag",
  90052: "CustomTimeStamp",
};

// Enumerated values for common FIX tags
export const FIX_VALUES = {
  35: {
    "0": "Heartbeat",
    "1": "Test Request",
    "2": "Resend Request",
    "3": "Reject",
    "4": "Sequence Reset",
    "5": "Logout",
    "6": "Indication of Interest",
    "7": "Advertisement",
    "8": "Execution Report",
    "9": "Order Cancel Reject",
    "A": "Logon",
    "D": "New Order Single",
    "F": "Order Cancel Request",
    "G": "Order Cancel/Replace Request",
    "H": "Order Status Request",
    "J": "Allocation Instruction",
    "P": "Allocation",
    "AK": "Allocation Report Ack",
    "AU": "Allocation Report",
  },

  // Side
  54: {
    1: "Buy",
    2: "Sell",
    3: "Buy minus",
    4: "Sell plus",
    5: "Sell short",
    6: "Sell short exempt",
    7: "Undisclosed",
    8: "Cross",
    9: "Cross short",
  },

  // OrdType
  40: {
    1: "Market",
    2: "Limit",
    3: "Stop",
    4: "Stop Limit",
    5: "Market on Close",
    6: "With or Without",
    7: "Limit or Better",
    8: "Limit with or Without",
    9: "On Basis",
    "D": "Stop on Bid/Offer",
    "P": "Pegged",
  },

  // TimeInForce
  59: {
    0: "Day",
    1: "Good Till Cancel (GTC)",
    2: "At the Opening",
    3: "Immediate or Cancel (IOC)",
    4: "Fill or Kill (FOK)",
    5: "Good Till Crossing",
    6: "Good Till Date",
  },

  // OrdStatus
  39: {
    0: "New",
    1: "Partially Filled",
    2: "Filled",
    3: "Done for Day",
    4: "Canceled",
    5: "Replaced",
    6: "Pending Cancel",
    7: "Stopped",
    8: "Rejected",
    9: "Suspended",
    "A": "Pending New",
    "B": "Calculated",
    "C": "Expired",
    "D": "Accepted for Bidding",
    "E": "Pending Replace",
  },

  // ExecType
  150: {
    0: "New",
    1: "Partial Fill",
    2: "Fill",
    3: "Done for Day",
    4: "Canceled",
    5: "Replaced",
    6: "Pending Cancel",
    7: "Stopped",
    8: "Rejected",
    9: "Suspended",
    "A": "Pending New",
    "B": "Calculated",
    "C": "Expired",
    "D": "Restated",
    "E": "Pending Replace",
    "F": "Trade",
    "G": "Trade Correct",
    "H": "Trade Cancel",
    "I": "Order Status",
  },

  // Rule 47 - Rule80A (OrderCapacity)
  47: {
    "A": "Agency single order",
    "C": "Agency batch order",
    "G": "Proprietary",
    "I": "Individual Investor",
    "N": "Proprietary firm",
    "R": "Riskless Principal",
    "W": "Agent for Other Member",
  },

  // ExecInst
  18: {
    1: "Not held",
    2: "Work",
    3: "Go along",
    4: "Over the day",
    5: "Held",
    6: "Participate don’t initiate",
    7: "Strict scale",
    8: "Try to scale",
    9: "Stay on bidside",
    "0": "Stay on offerside",
    "A": "No cross",
    "B": "OK to cross",
    "C": "Call first",
    "D": "Percent of volume",
    "E": "Do not increase",
    "F": "Do not reduce",
    "G": "All or none",
  },

  // HandlInst (21)
  21: {
    1: "Automated execution order, private, no broker intervention",
    2: "Automated execution order, public broker intervention OK",
    3: "Manual order, best execution",
  },

  // SecurityIDSource (22)
  22: {
    "1": "CUSIP",
    "2": "SEDOL",
    "3": "QUIK",
    "4": "ISIN number",
    "5": "RIC code",
    "6": "ISO Currency Code",
    "7": "ISO Country Code",
    "8": "Exchange Symbol",
    "9": "CTA Symbol",
    "A": "Bloomberg Symbol",
    "B": "Wertpapier",
    "C": "Dutch",
    "D": "Valoren",
    "E": "Sicovam",
    "F": "Belgian",
    "G": "Common",
    "H": "Clearing House / Clearing Organization",
    "I": "ISDA/FpML",
    "J": "Option Price Reporting Authority",
  },

  // BookingType (775)
  775: {
    0: "Regular booking",
    1: "CFD (Contract for Difference)",
    2: "Total Return Swap",
  },

  // Custom (Your example)
  7620: { 1: "VWAP", 2: "TWAP", 3: "CustomAlgo" },
  7722: { N: "Normal", Y: "Special" },
};
